services:
  default:
    build: .              # <-- Compose will use the Dockerfile above
    init: true
    command: sleep infinity

    volumes:
      - ../materials:/materials:ro

    # Compose v2+ GPU request (works with plain `docker compose`)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all          # or a number / specific IDs
              capabilities: [gpu] # generic GPU capability
              
    environment:
      PYTHONUNBUFFERED: "1"
